// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: events.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO system_events (
    public_key,
    policy_id,
    event_type,
    event_data
) VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertEventParams struct {
	PublicKey pgtype.Text
	PolicyID  pgtype.Text
	EventType interface{}
	EventData []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.PublicKey,
		arg.PolicyID,
		arg.EventType,
		arg.EventData,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
