// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PluginPolicy struct {
	ID            pgtype.UUID
	PublicKey     string
	PluginID      string
	PluginVersion string
	PolicyVersion string
	Signature     string
	Active        bool
	Recipe        string
	Deleted       bool
}
