// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PluginPolicy struct {
	ID            pgtype.UUID
	PublicKey     string
	PluginID      string
	PluginVersion string
	PolicyVersion string
	Signature     string
	Active        bool
	Recipe        string
	Deleted       bool
}

type SystemEvent struct {
	ID        int64
	PublicKey pgtype.Text
	PolicyID  pgtype.UUID
	EventType interface{}
	EventData []byte
	CreatedAt pgtype.Timestamp
}
